Repository kioku-project/kioku, pull requests merged in 2023-06, with the labels that each got.

#41 added logout & serializer simplifications
  backend/kioku-api.postman_collection.json
  backend/pkg/converter/fiberSerializerTypes.go
  backend/pkg/converter/typeConverter.go
  backend/services/frontend/handler/frontend.go
  backend/services/frontend/main.go
  frontend/components/navigation/Header.tsx
Labels: enhancement

#46 added due routes and minor fixes
  backend/kioku-api.postman_collection.json
  backend/pkg/converter/fiberSerializerTypes.go
  backend/services/frontend/handler/frontend.go
  backend/services/frontend/main.go
  backend/services/srs/handler/srs.go
  backend/services/srs/proto/srs.pb.go
  backend/services/srs/proto/srs.pb.micro.go
  backend/services/srs/proto/srs.proto
  backend/store/postgres.go
  backend/store/store.go
Labels: bug, enhancement

#47 fixed cardDelete when revlogs exist
  backend/pkg/model/card.go
Labels: bug

#48 naming hotfix for fiber serializer
  backend/pkg/converter/fiberSerializerTypes.go
  backend/pkg/converter/typeConverter.go
  backend/services/frontend/handler/frontend.go
  backend/services/user/handler/user.go
Labels: bug

#50 refactored and redesigned request/invitation logic for groups
  backend/pkg/converter/typeConverter.go
  backend/pkg/converter/typeConverter_test.go
  backend/pkg/helper/errors.go
  backend/pkg/model/groupAdmission.go
  backend/pkg/model/groupUserRole.go
  backend/services/collaboration/handler/collaboration.go
  backend/services/collaboration/proto/collaboration.pb.go
  backend/services/collaboration/proto/collaboration.pb.micro.go
  backend/services/collaboration/proto/collaboration.proto
  backend/services/collaboration/proto/health.pb.go
  backend/services/frontend/handler/frontend.go
  backend/services/frontend/main.go
  backend/store/postgres.go
  backend/store/store.go
Labels: enhancement
